version: '3'

services:
  db:
    container_name: db
    image: postgres:11
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reportabug_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    container_name: web
    build: .
    command: flask run -h 0.0.0.0 -p 8000
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/reportabug_db
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    volumes:
      - .:/usr/src/app/
    ports:
      - '8000:8000'
    restart: always
    depends_on: 
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on: 
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin: